# Generated by Django 6.1 on 2026-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='뉴스',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=200)),
                ('링크', models.URLField(unique=True)),
                ('시각', models.DateTimeField()),
                ('출처', models.CharField(max_length=20)),
                ('감성', models.CharField(blank=True, max_length=10)),
                ('신뢰도', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
