# Generated by Django 6.1 on 2026-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='내역',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.DateField()),
                ('분류', models.CharField(max_length=10)),
                ('항목', models.CharField(max_length=50)),
                ('금액', models.IntegerField()),
                ('이름', models.CharField(max_length=20)),
                ('계좌', models.CharField(max_length=30)),
            ],
        ),
    ]
