# Generated by Django 6.1 on 2026-08-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_내역_주인'),
    ]

    operations = [
        migrations.CreateModel(
            name='예측기록',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('항목', models.CharField(max_length=50)),
                ('분류', models.CharField(max_length=10)),
                ('확신', models.FloatField()),
                ('시각', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
