# Generated by Django 6.1 on 2026-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_예측기록'),
    ]

    operations = [
        migrations.CreateModel(
            name='수집',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.CharField(max_length=8)),
                ('이름', models.CharField(max_length=50)),
                ('값', models.FloatField()),
            ],
        ),
    ]
